"""books table

Revision ID: d57b3e25b0c1
Revises: 
Create Date: 2021-03-12 12:38:05.003356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd57b3e25b0c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('pdf_name', sa.String(length=512), nullable=False),
    sa.Column('book_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('pdf_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
